/**
 * Vite development server integration for Express
 * Handles both development (with HMR) and production (static files) modes
 *
 * @see https://vite.dev/guide/backend-integration - Vite Backend Integration Guide
 * @see https://vite.dev/guide/ssr#setting-up-the-dev-server - Vite SSR/Middleware Mode
 * @see https://vite.dev/guide/api-javascript#createserver - Vite JavaScript API
 */

import express, { type Express, Request, Response, NextFunction } from 'express';
import { createServer as createViteServer, ViteDevServer } from 'vite';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, '../..');

const isDev = process.env.NODE_ENV !== 'production';

/**
 * Manifest chunk structure as generated by Vite build
 * @see https://vite.dev/guide/backend-integration#backend-integration
 */
interface ManifestChunk {
  file: string;
  name?: string;
  src?: string;
  isEntry?: boolean;
  isDynamicEntry?: boolean;
  imports?: string[];
  dynamicImports?: string[];
  css?: string[];
  assets?: string[];
}

type Manifest = Record<string, ManifestChunk>;

/**
 * Configure Vite middleware for Express in development mode
 *
 * Creates Vite dev server in middleware mode which allows Express to handle routing
 * while Vite handles module transformation, HMR, and React Fast Refresh.
 *
 * @see https://vite.dev/guide/ssr#setting-up-the-dev-server - Middleware mode setup
 * @see https://vite.dev/config/server-options#server-middlewaremode - middlewareMode option
 * @see https://vite.dev/guide/api-javascript#transformindexhtml - transformIndexHtml API
 */
export async function setupViteDev(app: Express): Promise<ViteDevServer> {
  // Create Vite server in middleware mode
  // @see https://vite.dev/guide/api-javascript#createserver
  const vite = await createViteServer({
    server: {
      // Disable Vite's built-in HTML serving, let Express handle routing
      // @see https://vite.dev/config/server-options#server-middlewaremode
      middlewareMode: true,
      hmr: {
        // Use the same port as the Express server for HMR WebSocket
        port: 3000,
      },
    },
    // Don't inject Vite's default HTML handling
    appType: 'custom',
  });

  // Use Vite's Connect-compatible middleware
  // Handles module transformation and HMR
  // @see https://vite.dev/guide/ssr#setting-up-the-dev-server
  app.use(vite.middlewares);

  // Serve index.html with Vite transformations for all non-API routes
  app.use('*', async (req: Request, res: Response, next: NextFunction) => {
    try {
      const url = req.originalUrl;

      // Skip API routes - let Express handle them
      if (url.startsWith('/api')) {
        return next();
      }

      // Read the index.html file
      let template = readFileSync(resolve(root, 'index.html'), 'utf-8');

      // Apply Vite HTML transforms (inject Vite client, process script tags)
      // @see https://vite.dev/guide/api-javascript#transformindexhtml
      template = await vite.transformIndexHtml(url, template);

      // Inject React Refresh preamble for Hot Module Replacement
      // This is required for @vitejs/plugin-react to work properly
      // @see https://vite.dev/guide/backend-integration#backend-integration (React section)
      // @see https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#consistent-components-exports
      const reactRefreshScript = `
<script type="module">
  import RefreshRuntime from '/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>`;

      // Inject the preamble before the first script tag
      template = template.replace(
        '<script',
        `${reactRefreshScript}\n    <script`
      );

      res.status(200).set({ 'Content-Type': 'text/html' }).end(template);
    } catch (error) {
      if (error instanceof Error) {
        // Let Vite fix the stack trace to show the actual source location
        vite.ssrFixStacktrace(error);
        next(error);
      }
    }
  });

  return vite;
}

/**
 * Configure static file serving for production mode
 *
 * Serves pre-built assets from dist/client and uses manifest.json to inject
 * the correct script and CSS tags with hashed filenames into the HTML.
 *
 * @see https://vite.dev/guide/backend-integration#backend-integration
 */
export function setupProd(app: Express): void {
  const distPath = resolve(root, 'dist/client');
  const manifestPath = resolve(distPath, '.vite/manifest.json');

  // Serve static assets with aggressive caching
  app.use(
    express.static(distPath, {
      index: false, // Don't automatically serve index.html
      maxAge: '1y', // Cache static assets for a year (they have hashed names)
    })
  );

  // Load the Vite build manifest
  // The manifest maps source files to their hashed output filenames
  // @see https://vite.dev/guide/backend-integration#backend-integration
  let manifest: Manifest = {};
  if (existsSync(manifestPath)) {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  }

  // Serve index.html for all non-API routes (SPA routing)
  app.use('*', (req: Request, res: Response, next: NextFunction) => {
    try {
      const url = req.originalUrl;

      // Skip API routes
      if (url.startsWith('/api')) {
        return next();
      }

      // Read the built index.html
      const indexPath = resolve(distPath, 'index.html');
      if (!existsSync(indexPath)) {
        return next(new Error('index.html not found. Run `npm run build` first.'));
      }

      let html = readFileSync(indexPath, 'utf-8');

      // Inject scripts and styles from manifest
      // The entry point is 'src/frontend/app.tsx' as defined in vite.config.ts
      const entry = manifest['src/frontend/app.tsx'];
      if (entry) {
        const { scripts, styles } = resolveManifestEntry(entry, manifest);

        // Inject CSS link tags before </head>
        // Order matters: CSS should be loaded before scripts
        if (styles.length > 0) {
          const styleLinks = styles
            .map((file) => `<link rel="stylesheet" href="/${file}">`)
            .join('\n    ');
          html = html.replace('</head>', `${styleLinks}\n  </head>`);
        }

        // Inject script module tags before </body>
        // These are ES modules with type="module"
        if (scripts.length > 0) {
          const scriptTags = scripts
            .map((file) => `<script type="module" src="/${file}"></script>`)
            .join('\n    ');
          html = html.replace('</body>', `${scriptTags}\n  </body>`);
        }
      }

      res.status(200).set({ 'Content-Type': 'text/html' }).end(html);
    } catch (error) {
      next(error);
    }
  });
}

/**
 * Resolve all scripts and styles for a manifest entry
 *
 * Recursively traverses the dependency graph to collect all CSS and JS files
 * needed for a given entry point. This ensures all dependencies are loaded
 * in the correct order.
 *
 * @see https://vite.dev/guide/backend-integration#backend-integration
 */
function resolveManifestEntry(
  entry: ManifestChunk,
  manifest: Manifest
): { scripts: string[]; styles: string[] } {
  const scripts: string[] = [];
  const styles: string[] = [];
  const visited = new Set<string>();

  function traverse(chunk: ManifestChunk) {
    // Avoid infinite loops in circular dependencies
    const key = chunk.file;
    if (visited.has(key)) return;
    visited.add(key);

    // Collect CSS files from this chunk
    if (chunk.css) {
      styles.push(...chunk.css);
    }

    // Add the chunk's JS file if it's an entry or dynamic entry
    if (chunk.isEntry || chunk.isDynamicEntry) {
      scripts.push(chunk.file);
    }

    // Recursively process imported chunks
    if (chunk.imports) {
      for (const importKey of chunk.imports) {
        const importedChunk = manifest[importKey];
        if (importedChunk) {
          traverse(importedChunk);
        }
      }
    }
  }

  traverse(entry);

  return { scripts, styles };
}

/**
 * Setup Vite integration based on NODE_ENV
 *
 * - Development: Runs Vite dev server with HMR
 * - Production: Serves pre-built static files
 *
 * @returns ViteDevServer instance in dev mode, null in production
 */
export async function setupVite(app: Express): Promise<ViteDevServer | null> {
  if (isDev) {
    console.log('🔧 Running in development mode with Vite HMR');
    return await setupViteDev(app);
  } else {
    console.log('📦 Running in production mode with static files');
    setupProd(app);
    return null;
  }
}
